CREATE TABLE BOOKING
(
    ID                 SERIAL PRIMARY KEY,
    CUSTOMER_ID        INTEGER,
    STAFF_ID           INTEGER   NOT NULL,
    BOOKING_DATE       DATE      NOT NULL,
    START_TIME         TIME      NOT NULL,
    END_TIME           TIME,
    CREATED_DATE       TIMESTAMP NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE BOOKING ADD CONSTRAINT FK_BOOKING_CUSTOMER foreign key (CUSTOMER_ID) references CUSTOMER (ID);