CREATE TABLE CUSTOMER
(
    ID      SERIAL PRIMARY KEY,
    NAME    VARCHAR(32) NOT NULL,
    SURNAME VARCHAR(32) NOT NULL,
    EMAIL   VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE CUSTOMER ADD CONSTRAINT UN_EMAIL UNIQUE (EMAIL);