CREATE TABLE VEHICLE
(
    ID                 SERIAL PRIMARY KEY,
    DRIVER_NAME        VARCHAR(32) NOT NULL,
    LICENCE_PLATE      VARCHAR(16) NOT NULL,
    CREATED_DATE       TIMESTAMP   NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE VEHICLE ADD CONSTRAINT UN_LICENCE_PLATE UNIQUE (LICENCE_PLATE);