CREATE TABLE STAFF
(
    ID                 SERIAL PRIMARY KEY,
    NAME               VARCHAR(32) NOT NULL,
    SURNAME            VARCHAR(32) NOT NULL,
    AGE                INTEGER     NOT NULL,
    GENDER             VARCHAR(8)  NOT NULL,
    VEHICLE_ID         BIGINT      NOT NULL,
    CREATED_DATE       TIMESTAMP   NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE STAFF ADD CONSTRAINT FK_STAFF_VEHICLE foreign key (VEHICLE_ID) references VEHICLE (ID);